### ISSUE TITLE
Can't build - error E0554

### ISSUE THREAD

**Issue by kissste** [iliazeus/iso2god-rs#11]
using: rustc 1.75.0 (82e1608df 2023-12-21)

   Compiling iso2god v1.4.8 (/home/aaa/iso2god-rs)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:1:12
  |
1 | #![feature(duration_constants)]
  |            ^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:2:12
  |
2 | #![feature(seek_stream_len)]
  |            ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `iso2god` (lib) due to 2 previous errors

**Comment by kissste** [comment]
worked with

rustup default nightly

**Comment by iliazeus** [comment]
FYI, the code now builds with stable Rust without issues.
