### ISSUE TITLE
Support Original Xbox `.XBE` Executables

### ISSUE THREAD

**Issue by halotroop2288** [iliazeus/iso2god-rs#13]
This lacks one key feature of the original program: Being able to use it with Original Xbox games.

When this is used with Original Xbox ISO files, it throws this error and then exits:

```
extracting ISO metadata
Error: default.xex file not found
```

It should instead look for a `default.xbe` if necessary.

**Comment by professor-jonny** [comment]
I think you need to convert them to a supported iso format with C-Xbox Tool, well at least you do have to with other tools.

https://www.xbox-hq.com/html/modules.php?name=Xbox_Homebrew&op=view&gid=291&title=C-Xbox+Tool

**Comment by Coolumin** [comment]
> I think you need to convert them to a supported iso format with C-Xbox Tool, well at least you do have to with other tools.
> 
> https://www.xbox-hq.com/html/modules.php?name=Xbox_Homebrew&op=view&gid=291&title=C-Xbox+Tool

No, it doesn't support OGX games at all. Even if you truncate the video partition of a "Redump" ISO or convert it into a XISO, it will show the same error about a missing default.xex.

**Comment by iliazeus** [comment]
Implemented in [v1.6.0](https://github.com/iliazeus/iso2god-rs/releases/tag/v1.6.0) via https://github.com/iliazeus/iso2god-rs/pull/20.
