### ISSUE TITLE
error: could not compile `iso2god`. "178  if fs::exists(path) not found in `fs` "

### ISSUE THREAD

**Issue by VitovEM** [iliazeus/iso2god-rs#17]
When I try to compile a project using cargo run, I get the following error:
  Compiling iso2god v1.5.1 (/opt/iso2god-rs)
error[E0425]: cannot find function `exists` in module `fs`
   --> src/bin/iso2god.rs:178:12
       |
178 | if fs::exists(path)? {
        |         ^^^^^^ not found in `fs`

For more information about this error, try `rustc --explain E0425`.

**Comment by iliazeus** [comment]
As of now, this project does not compile with stable Rust, only beta and nightly versions.

See #15 if you still need to use stable.

**Comment by iliazeus** [comment]
Rust 1.81 is out, and the current code now builds with stable Rust without issues.
