### ISSUE TITLE
error[E0425]: cannot find function `exists` in module `fs` (and fix)

### ISSUE THREAD

**Issue by SnepOMatic** [iliazeus/iso2god-rs#18]
Building from source using rustc 1.80.1 I was hitting "error[E0425]: cannot find function `exists` in module `fs`"
In this case src\bin\iso2god.rs line 178

Changing:
`fs::exists(path)?`
to
`path.try_exists()?`

Fixed the issue.

I apologise for lack of PR as I can't right now (plus my 'fix' may be skimming over something important), but may be useful for someone stuck?

**Comment by iliazeus** [comment]
See #15 and #17.

Right now, this project only builds with nightly Rust (and probably already does with beta).

**Comment by iliazeus** [comment]
Rust 1.81 is out, and the current code now builds with stable Rust without issues.
