### ISSUE TITLE
XBLA in unity query

### ISSUE THREAD

**Issue by thomasbra1** [iliazeus/iso2god-rs#3]
I have seen this a few times in testing.

Error: error querying XboxUnity; try --offline flag

Caused by:
    0: error decoding response body: unknown variant `XBLA`, expected one of ``, `360`, `Xbox1` at line 1 column 110
    1: unknown variant `XBLA`, expected one of ``, `360`, `Xbox1` at line 1 column 110

From checking gamefaqs on a few titles it means that the game was released on disc and digitally and xboxunity seems to be picking XBLA for the entry but the data is the same for both.   Both XBLA and 360 would be valid return data.

**Comment by iliazeus** [comment]
Can you please give an example of a title that this happens with? Just the name would be enough.

**Comment by thomasbra1** [comment]
XBLA
-------------
Wipeout 3

querying XboxUnity for title ID 415608DD
Error: error querying XboxUnity; try --offline flag

Caused by:
    0: error decoding response body: unknown variant `XBLA`, expected one of ``, `360`, `Xbox1` at line 1 column 110
    1: unknown variant `XBLA`, expected one of ``, `360`, `Xbox1` at line 1 column 110

Default XEX
-----------------
   Some games have the default.exe with a capital D (Default.xex) so they are not found (couple examples below)
   007 Legends (USA) (En,Fr,De).iso 
   AFL Live 2 (Australia).iso

Can't find default.exe even though present
---------------------------------------------------------
Adventure Time - Explore the Dungeon Because I Don'\''t Know! (USA, Europe).iso

**Comment by iliazeus** [comment]
Thank you! Can you please create separate issues for the last two errors?
