### ISSUE TITLE
Some games have the default.exe with a capital D (Default.xex) so they are not found 

### ISSUE THREAD

**Issue by thomasbra1** [iliazeus/iso2god-rs#4]
Default XEX
Some games have the default.exe with a capital D (Default.xex) so they are not found (couple examples below)
007 Legends (USA) (En,Fr,De).iso
AFL Live 2 (Australia).iso

**Comment by iliazeus** [comment]
Should be fixed in [v1.4.7](https://github.com/iliazeus/iso2god-rs/releases/tag/v1.4.7).
