### ISSUE TITLE
Multi Disc games overwrite previous disc

### ISSUE THREAD

**Issue by thomasbra1** [iliazeus/iso2god-rs#6]

**Comment by thomasbra1** [comment]
The XBOX360 has some games that span more than one disc.  They share the same title id.  Given the structure of the GOD output is to use the title id as the folder name disc 2 will overwrite disc 1 and so on.

I only use verified redump images for reporting issues.

**Comment by professor-jonny** [comment]
I believe you are mistaken as those games would be un installable via the native NXE format if that were the case.

Many multi disk games have a content folder that is to be installed using the on disk installer and the other disk is to be installed via the dash as normal.

The folder structure should be something like:
content\545407F2\00007000
and the data will be stored in
content\545407F2\0000D000

can you list/ provide a link to a title that has this issue?

**Comment by thomasbra1** [comment]
I have attached a screenshot of the one I have seen.  It may or may not be a one off.
GOD1 = Disc 1 , GOD2 = Disc 2
![Selection_042](https://user-images.githubusercontent.com/25257905/235794835-84abd6ad-81e9-4d7d-91c1-908b5747fa4a.png)

**Comment by thomasbra1** [comment]
Out of curiosity I converted them with the original windows version and below are the results.  It creates a long hex number for each.  No idea how it calculates it but I did a second run and it was the same.

![Selection_045](https://user-images.githubusercontent.com/25257905/235798904-5e94ba3c-8c05-40d7-a0dd-feaf8ba30e9f.png)

**Comment by professor-jonny** [comment]
That is correct there is two data directorys under 00007000 there is two disks present.
