### ISSUE TITLE
Static binary for linux

### ISSUE THREAD

**Issue by That-Dude** [iliazeus/iso2god-rs#7]
Hi

Would it be possible to create a [static binary](https://msfjarvis.dev/posts/building-static-rust-binaries-for-linux/) for linux?

Use case, it would like to run this on my unRAID NAS where I have a stack of ISO that I want to convert, but unRAID has a very limited slack build that lacks libssl.so.3, libcrypto.so.3 etc required by your app.

Thanks, Dan

**Comment by That-Dude** [comment]
Never-mind, I figured it out. Rust error messages are amazing! It literally told everything I need to do to get the static binary build - essentially install rust nightly and devssl.

**Comment by iliazeus** [comment]
@That-Dude I've removed the libssl dependency, and right now the tool does not do any http requests at all. So you might be able to use a "default" build right now, without using static linking.

I haven't checked if that works though, but thought you might be interested in that!
